export const ROUTES = {
  LOGIN: "/",
  DASHBOARD: "/home",
  TUTORS: "/tutors",
  STUDENTS: "/students",
  SUBJECTS: "/subjects",
  COURSES: "/courses",
  PAYMENT_INFO: "/payment-info",
  BLOGS: "/blogs",
  MANAGE_BLOG: "/manage-blog",
  MANAGE_STUDENT: "/manage-student",
  MANAGE_TUTOR: "/manage-tutor",
  FAQS: "/faqs",
  TESTIMONIALS: "/testimonials",
  CONTACT_US: "/contact-us",
};
